name: Build, Test

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - uses: actions/upload-artifact@master
        with:
          name: solution-folder
          path: ./

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: solution-folder
          path: ./
      - name: Test
        run: cd test && dotnet test --verbosity normal
