name: Build, Test, Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - uses: actions/upload-artifact@master
        with:
          name: solution-folder
          path: ./

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: solution-folder
          path: ./
      - name: Test
        run: ls && dotnet test --no-build --verbosity normal

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: solution-folder
          path: ./
      - name: Pack
        run: dotnet pack
      - name: Publish
        run: |
          CURRENT_VERSION=$(< .nuspec grep -oP '\<version\>(.*)\</version\>' | sed 's/[version<>/]//g') &&
          cd /home/runner/work/fazor/fazor/bin/Debug/ &&
          dotnet nuget push fazor.$CURRENT_VERSION.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.API_KEY}} --skip-duplicate
